from selenium import webdriver
from selenium.webdriver import ActionChains, Keys
from selenium.webdriver.common.by import By
import time


class Sasi_project2_task5():

    def personal(self):

        driver = webdriver.Firefox()
        url1 = "https://opensource-demo.orangehrmlive.com/web/index.php/auth/login"
        driver.get(url1)
        driver.maximize_window()
        time.sleep(3)
        username = driver.find_element(By.XPATH, "//input[@name='username']")
        username.send_keys("Admin")
        time.sleep(3)
        password = driver.find_element(By.XPATH, "//input[@name='password']")
        password.send_keys("admin123")
        time.sleep(3)
        driver.find_element(By.XPATH, "//button[@type='submit']").click()
        time.sleep(3)
        driver.find_element(By.XPATH, "//span[text()='PIM']").click()
        time.sleep(3)
        driver.find_element(By.XPATH, "//div[contains(text(),'Sasi Kiran')").click()
        time.sleep(3)
        nickname = driver.find_element(By.XPATH, "//label[text()='Nickname']/following::div[1]/input")
        time.sleep(3)
        nickname.send_keys("Raven")
        time.sleep(3)
        other_ID = driver.find_element(By.XPATH, "//label[text()='Other Id']/following::div[1]/input")
        other_ID.send_keys("1208")
        time.sleep(3)
        licensenumber = driver.find_element(By.XPATH, "(//label[text()='Driver's License Number']/following::div["
                                                      "1]/input")
        licensenumber.send_keys("987456")
        time.sleep(3)
        expire_date = driver.find_element(By.XPATH, "(//input[@placeholder='mm-dd-yyyy'])[1]")
        expire_date.send_keys("03-10-2030")
        time.sleep(3)
        ssnumber = driver.find_element(By.XPATH, "(//input)/[10]")
        ssnumber.send_keys("112")
        sinnumber = driver.find_element(By.XPATH, "(//input)/[11]")
        sinnumber.send_keys("951")
        time.sleep(3)
        nationality = driver.find_element(By.XPATH, "//label[text()='Nationality']/following::div[1]")
        actions = ActionChains(driver)
        ActionChains(driver).move_to_element(nationality).click().perform()
        selecting = driver.find_element(By.XPATH, "//div[@role='option']/span[text()='Indian']")
        ActionChains(driver).move_to_element(selecting).click().perform()
        time.sleep(6)
        marital = driver.find_element(By.XPATH, "//label[text()='Marital Status']/following::div[1]")
        ActionChains(driver).move_to_element(marital).click().perform()
        status = driver.find_element(By.XPATH, "//div[@role='option']/span[text()='Single']")
        ActionChains(driver).move_to_element(status).click().perform()
        time.sleep(6)
        dob = driver.find_element(By.XPATH, "(//input[@placeholder='mm-dd-yyyy'])[2]")
        dob.send_keys("08-12-1998")
        time.sleep(3)
        gender = driver.find_element(By.XPATH, "//label[normalize-space()='Male']")
        gender.is_selected()
        time.sleep(3)
        military = driver.find_element(By.XPATH, "(//input)/[15]")
        military.send_keys("Nil")
        time.sleep(3)
        save = driver.find_element(By.XPATH, "//button[@type='submit']")
        save.click()
        time.sleep(3)
        blood = driver.find_element(By.XPATH, "//label[text()='Blood Type']/following::div[1]")
        ActionChains(driver).move_to_element(blood).click().perform()
        type = driver.find_element(By.XPATH, "//div[@role='option']/span[text()='A+']")
        ActionChains(driver).move_to_element(type).click().perform()
        time.sleep(6)
        save = driver.find_element(By.XPATH, "//button[@type='submit']")
        save.click()
        time.sleep(3)


personal_info = Sasi_project2_task5()
personal_info.personal()